"""create otp table

Revision ID: d0ff91453b5d
Revises: 6fea5f7ca0fa
Create Date: 2026-03-03 10:35:13.399525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0ff91453b5d'
down_revision = '6fea5f7ca0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_allocations_all_ledger_entry_id'))

    op.drop_table('bill_allocations')
    with op.batch_alter_table('sync_context_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_context_attempts_sync_context_id'))
        batch_op.drop_index(batch_op.f('ix_sync_context_attempts_sync_session_id'))

    op.drop_table('sync_context_attempts')
    with op.batch_alter_table('mailing_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mailing_detail_ledger_guid'))

    op.drop_table('mailing_detail')
    with op.batch_alter_table('multi_address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_multi_address_ledger_guid'))

    op.drop_table('multi_address')
    with op.batch_alter_table('contact_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_detail_ledger_guid'))

    op.drop_table('contact_detail')
    with op.batch_alter_table('hsn_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hsn_detail_ledger_guid'))

    op.drop_table('hsn_detail')
    with op.batch_alter_table('vch_batch_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vch_batch_allocations_base_inventory_entry_id'))

    op.drop_table('vch_batch_allocations')
    with op.batch_alter_table('vch_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vch_ledger_entries_all_inventory_entries_id'))
        batch_op.drop_index(batch_op.f('ix_vch_ledger_entries_voucher_guid'))

    op.drop_table('vch_ledger_entries')
    with op.batch_alter_table('error_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_info_sync_context_id'))

    op.drop_table('error_info')
    with op.batch_alter_table('state_wise_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_wise_detail_gst_detail_id'))

    op.drop_table('state_wise_detail')
    with op.batch_alter_table('ledger_gst_registration_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_gst_registration_detail_ledger_guid'))

    op.drop_table('ledger_gst_registration_detail')
    with op.batch_alter_table('sync_context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_context_sync_session_id'))

    op.drop_table('sync_context')
    with op.batch_alter_table('gst_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gst_detail_ledger_guid'))

    op.drop_table('gst_detail')
    op.drop_table('ledgers')
    with op.batch_alter_table('gst_rate_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gst_rate_detail_state_wise_detail_id'))

    op.drop_table('gst_rate_detail')
    with op.batch_alter_table('sync_session_object_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_session_object_stats_sync_session_id'))

    op.drop_table('sync_session_object_stats')
    with op.batch_alter_table('sync_pointers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_pointers_company_id'))

    op.drop_table('sync_pointers')
    op.drop_table('__efmigrationshistory')
    with op.batch_alter_table('vch_inventory_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vch_inventory_entries_all_ledger_entry_id'))
        batch_op.drop_index(batch_op.f('ix_vch_inventory_entries_voucher_guid'))

    op.drop_table('vch_inventory_entries')
    op.drop_table('groups')
    with op.batch_alter_table('sync_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_sessions_company_id'))

    op.drop_table('sync_sessions')
    with op.batch_alter_table('excise_jurisdiction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excise_jurisdiction_multi_address_id'))

    op.drop_table('excise_jurisdiction')
    op.drop_table('vouchers')
    op.drop_table('otp_verifications')
    with op.batch_alter_table('sync_stats_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_stats_snapshots_sync_session_id'))

    op.drop_table('sync_stats_snapshots')
    with op.batch_alter_table('language_name_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_language_name_list_group_guid'))
        batch_op.drop_index(batch_op.f('ix_language_name_list_ledger_guid'))

    op.drop_table('language_name_list')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('guid',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['guid'])
        batch_op.drop_column('is_bill_wise_on')
        batch_op.drop_column('fax_number')
        batch_op.drop_column('formal_name')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('cin')
        batch_op.drop_column('integrate_accountswith_inventory')
        batch_op.drop_column('is_tcs_on')
        batch_op.drop_column('starting_from')
        batch_op.drop_column('is_group_company')
        batch_op.drop_column('is_tds_on')
        batch_op.drop_column('website')
        batch_op.drop_column('state')
        batch_op.drop_column('is_payroll_on')
        batch_op.drop_column('track_changes_from')
        batch_op.drop_column('pan')
        batch_op.drop_column('tds_deductor_branch')
        batch_op.drop_column('intial_sync_completed')
        batch_op.drop_column('tan_number')
        batch_op.drop_column('is_gst_on')
        batch_op.drop_column('tan_reg_number')
        batch_op.drop_column('is_interest_on')
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('is_context_builded')
        batch_op.drop_column('country')
        batch_op.drop_column('sync_from')
        batch_op.drop_column('last_sync')
        batch_op.drop_column('comp_num')
        batch_op.drop_column('pin_code')
        batch_op.drop_column('books_from')
        batch_op.drop_column('tds_deductor_type')
        batch_op.drop_column('end_date')
        batch_op.drop_column('is_cost_centers_on')
        batch_op.drop_column('is_inventory_on')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_inventory_on', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_cost_centers_on', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('end_date', mysql.DATETIME(fsp=6), nullable=True))
        batch_op.add_column(sa.Column('tds_deductor_type', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('books_from', mysql.DATETIME(fsp=6), nullable=False))
        batch_op.add_column(sa.Column('pin_code', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('comp_num', mysql.LONGTEXT(), nullable=False))
        batch_op.add_column(sa.Column('last_sync', mysql.DATETIME(fsp=6), nullable=False))
        batch_op.add_column(sa.Column('sync_from', mysql.DATETIME(fsp=6), nullable=False))
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_context_builded', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mobile_number', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_interest_on', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tan_reg_number', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_gst_on', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tan_number', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('intial_sync_completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tds_deductor_branch', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('pan', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('track_changes_from', mysql.DATETIME(fsp=6), nullable=False))
        batch_op.add_column(sa.Column('is_payroll_on', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_tds_on', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_group_company', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('starting_from', mysql.DATETIME(fsp=6), nullable=True))
        batch_op.add_column(sa.Column('is_tcs_on', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('integrate_accountswith_inventory', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cin', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('formal_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('fax_number', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_bill_wise_on', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('guid',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    op.create_table('language_name_list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_guid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ledger_guid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('names', mysql.LONGTEXT(), nullable=False),
    sa.Column('language_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_guid'], ['groups.guid'], name=op.f('fk_language_name_list_groups_group_guid')),
    sa.ForeignKeyConstraint(['ledger_guid'], ['ledgers.guid'], name=op.f('fk_language_name_list_ledgers_ledger_guid')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('language_name_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_language_name_list_ledger_guid'), ['ledger_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_language_name_list_group_guid'), ['group_guid'], unique=False)

    op.create_table('sync_stats_snapshots',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sync_session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('captured_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('master_stats_json', mysql.LONGTEXT(), nullable=True),
    sa.Column('master_last_alter_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('voucher_stats_json', mysql.LONGTEXT(), nullable=True),
    sa.Column('voucher_last_alter_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sync_session_id'], ['sync_sessions.id'], name=op.f('fk_sync_stats_snapshots_sync_sessions_sync_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sync_stats_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_stats_snapshots_sync_session_id'), ['sync_session_id'], unique=True)

    op.create_table('otp_verifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('otp_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('attempts', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vouchers',
    sa.Column('guid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remote_id', mysql.LONGTEXT(), nullable=False),
    sa.Column('master_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('alter_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('entered_by', mysql.LONGTEXT(), nullable=True),
    sa.Column('altered_by', mysql.LONGTEXT(), nullable=True),
    sa.Column('altered_on', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('date', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('effective_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('reference_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('reference', mysql.LONGTEXT(), nullable=True),
    sa.Column('voucher_type', mysql.LONGTEXT(), nullable=False),
    sa.Column('view', mysql.LONGTEXT(), nullable=False),
    sa.Column('voucher_gst_class', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_cost_centre', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('cost_centre_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('voucher_entry_mode', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_invoice', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('voucher_number', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_optional', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('narration', mysql.LONGTEXT(), nullable=True),
    sa.Column('price_level', mysql.LONGTEXT(), nullable=True),
    sa.Column('bill_to_place', mysql.LONGTEXT(), nullable=True),
    sa.Column('irn', mysql.LONGTEXT(), nullable=True),
    sa.Column('irn_ack_no', mysql.LONGTEXT(), nullable=True),
    sa.Column('irn_ack_date', mysql.LONGTEXT(), nullable=True),
    sa.Column('dispatch_from_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('dispatch_from_state_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('dispatch_from_pin_code', mysql.LONGTEXT(), nullable=True),
    sa.Column('dispatch_from_place', mysql.LONGTEXT(), nullable=True),
    sa.Column('delivery_notes_shipping_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('delivery_notes_delivery_note', mysql.LONGTEXT(), nullable=True),
    sa.Column('dispatch_doc_no', mysql.LONGTEXT(), nullable=True),
    sa.Column('basic_shipped_by', mysql.LONGTEXT(), nullable=True),
    sa.Column('destination', mysql.LONGTEXT(), nullable=True),
    sa.Column('carrier_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('billof_landing_no', mysql.LONGTEXT(), nullable=True),
    sa.Column('billof_landing_date', mysql.LONGTEXT(), nullable=True),
    sa.Column('place_of_receipt', mysql.LONGTEXT(), nullable=True),
    sa.Column('ship_or_flight_no', mysql.LONGTEXT(), nullable=True),
    sa.Column('landing_port', mysql.LONGTEXT(), nullable=True),
    sa.Column('discharge_port', mysql.LONGTEXT(), nullable=True),
    sa.Column('destination_country', mysql.LONGTEXT(), nullable=True),
    sa.Column('shipping_bill_no', mysql.LONGTEXT(), nullable=True),
    sa.Column('shipping_bill_date', mysql.LONGTEXT(), nullable=True),
    sa.Column('port_code', mysql.LONGTEXT(), nullable=True),
    sa.Column('basic_due_dateof_payment', mysql.LONGTEXT(), nullable=True),
    sa.Column('order_reference', mysql.LONGTEXT(), nullable=True),
    sa.Column('party_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('voucher_number_series', mysql.LONGTEXT(), nullable=True),
    sa.Column('party_mailing_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('state', mysql.LONGTEXT(), nullable=True),
    sa.Column('country', mysql.LONGTEXT(), nullable=True),
    sa.Column('gst_registration', mysql.LONGTEXT(), nullable=True),
    sa.Column('registration_type', mysql.LONGTEXT(), nullable=True),
    sa.Column('party_gstin', mysql.LONGTEXT(), nullable=True),
    sa.Column('place_of_supply', mysql.LONGTEXT(), nullable=True),
    sa.Column('pin_code', mysql.LONGTEXT(), nullable=True),
    sa.Column('consignee_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('consignee_mailing_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('consignee_state', mysql.LONGTEXT(), nullable=True),
    sa.Column('consignee_country', mysql.LONGTEXT(), nullable=True),
    sa.Column('consignee_gstin', mysql.LONGTEXT(), nullable=True),
    sa.Column('consignee_pin_code', mysql.LONGTEXT(), nullable=True),
    sa.Column('address', mysql.LONGTEXT(), nullable=True),
    sa.Column('buyer_address', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_cancelled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('override_e_way_bill_applicability', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('guid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('excise_jurisdiction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('multi_address_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('applicable_from', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('range', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('division', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('commissionerate', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['multi_address_id'], ['multi_address.id'], name=op.f('fk_excise_jurisdiction_multi_address_multi_address_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('excise_jurisdiction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excise_jurisdiction_multi_address_id'), ['multi_address_id'], unique=False)

    op.create_table('sync_sessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sync_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('completed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('status', mysql.LONGTEXT(), nullable=False),
    sa.Column('error_message', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sync_sessions_companies_company_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sync_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_sessions_company_id'), ['company_id'], unique=False)

    op.create_table('groups',
    sa.Column('guid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('group_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remote_id', mysql.LONGTEXT(), nullable=False),
    sa.Column('master_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('alter_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('entered_by', mysql.LONGTEXT(), nullable=True),
    sa.Column('altered_by', mysql.LONGTEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('alias', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('parent', mysql.LONGTEXT(), nullable=True),
    sa.Column('reserved_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_revenue', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_deemed_positive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('affect_gross_profit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_subledger', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('sort_position', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('addl_alloc_type', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('is_calculable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_addable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('guid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vch_inventory_entries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_item_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('voucher_guid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('inventory_entry_type', mysql.VARCHAR(length=34), nullable=False),
    sa.Column('all_ledger_entry_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_descriptions', mysql.LONGTEXT(), nullable=False),
    sa.Column('index_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_item_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('bom_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_scrap', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('discount', mysql.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('is_deemed_positive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('rate_rate', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('rate_forex_rate', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('rate_unit', mysql.LONGTEXT(), nullable=True),
    sa.Column('actual_quantity_unit', mysql.LONGTEXT(), nullable=True),
    sa.Column('actual_quantity_quantity', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('billed_quantity_unit', mysql.LONGTEXT(), nullable=True),
    sa.Column('billed_quantity_quantity', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_amount', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('amount_forex_amount', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_forex_currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('amount_rate_of_exchange', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_is_debit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['all_ledger_entry_id'], ['vch_ledger_entries.id'], name=op.f('fk_vch_inventory_entries_vch_ledger_entries_all_ledger_entry_id')),
    sa.ForeignKeyConstraint(['voucher_guid'], ['vouchers.guid'], name=op.f('fk_vch_inventory_entries_vouchers_voucher_guid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vch_inventory_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vch_inventory_entries_voucher_guid'), ['voucher_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_vch_inventory_entries_all_ledger_entry_id'), ['all_ledger_entry_id'], unique=False)

    op.create_table('__efmigrationshistory',
    sa.Column('migration_id', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('product_version', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('migration_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sync_pointers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('object_name', mysql.LONGTEXT(), nullable=False),
    sa.Column('last_tally_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_updated', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sync_pointers_companies_company_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sync_pointers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_pointers_company_id'), ['company_id'], unique=False)

    op.create_table('sync_session_object_stats',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sync_session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('object_type', mysql.LONGTEXT(), nullable=False),
    sa.Column('created_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('edited_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deleted_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sync_session_id'], ['sync_sessions.id'], name=op.f('fk_sync_session_object_stats_sync_sessions_sync_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sync_session_object_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_session_object_stats_sync_session_id'), ['sync_session_id'], unique=False)

    op.create_table('gst_rate_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state_wise_detail_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duty_head', mysql.LONGTEXT(), nullable=True),
    sa.Column('valuation_type', mysql.LONGTEXT(), nullable=True),
    sa.Column('gst_rate', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['state_wise_detail_id'], ['state_wise_detail.id'], name=op.f('fk_gst_rate_detail_state_wise_detail_state_wise_detail_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('gst_rate_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gst_rate_detail_state_wise_detail_id'), ['state_wise_detail_id'], unique=False)

    op.create_table('ledgers',
    sa.Column('guid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('remote_id', mysql.LONGTEXT(), nullable=False),
    sa.Column('master_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('alter_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('entered_by', mysql.LONGTEXT(), nullable=True),
    sa.Column('altered_by', mysql.LONGTEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('alias', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('group', mysql.LONGTEXT(), nullable=True),
    sa.Column('opening_balance_amount', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('opening_balance_currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('opening_balance_forex_amount', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('opening_balance_forex_currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('opening_balance_rate_of_exchange', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('opening_balance_is_debit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('tax_type', mysql.LONGTEXT(), nullable=True),
    sa.Column('gst_tax_type', mysql.LONGTEXT(), nullable=True),
    sa.Column('rateof_tax', mysql.FLOAT(), nullable=True),
    sa.Column('appropriate_for', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_bill_wise', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_cost_centres_on', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_interest_on', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_credit_check', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('credit_limit', mysql.LONGTEXT(), nullable=True),
    sa.Column('e_mail', mysql.LONGTEXT(), nullable=True),
    sa.Column('e_mail_cc', mysql.LONGTEXT(), nullable=True),
    sa.Column('website', mysql.LONGTEXT(), nullable=True),
    sa.Column('pan_number', mysql.LONGTEXT(), nullable=True),
    sa.Column('gst_type_of_supply', mysql.LONGTEXT(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('guid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('gst_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ledger_guid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('applicable_from', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('calculation_type', mysql.LONGTEXT(), nullable=True),
    sa.Column('calculate_slab_on_mrp', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('nature_of_transaction', mysql.LONGTEXT(), nullable=False),
    sa.Column('is_non_gst_goods', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('taxability', mysql.LONGTEXT(), nullable=False),
    sa.Column('source_of_gst_details', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_reverse_charge_applicable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_in_eligiblefor_itc', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('include_exp_for_slab_calc', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ledger_guid'], ['ledgers.guid'], name=op.f('fk_gst_detail_ledgers_ledger_guid')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('gst_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gst_detail_ledger_guid'), ['ledger_guid'], unique=False)

    op.create_table('sync_context',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('object_type', mysql.LONGTEXT(), nullable=False),
    sa.Column('from_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('to_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('voucher_type_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('page_size', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_count', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('total_pages', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_synced_page', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_fully_synced', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('lower_bound', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('upper_bound', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sync_type', mysql.LONGTEXT(), nullable=False),
    sa.Column('updatedat', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('sync_session_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sync_session_id'], ['sync_sessions.id'], name=op.f('fk_sync_context_sync_sessions_sync_session_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sync_context', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_context_sync_session_id'), ['sync_session_id'], unique=False)

    op.create_table('ledger_gst_registration_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ledger_guid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('applicable_from', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('gst_registration_type', mysql.LONGTEXT(), nullable=False),
    sa.Column('state', mysql.LONGTEXT(), nullable=True),
    sa.Column('place_of_supply', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_other_territory_assesse', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('consider_purchase_for_export', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_transporter', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('transporter_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_common_party', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('gstin', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_guid'], ['ledgers.guid'], name=op.f('fk_ledger_gst_registration_detail_ledgers_ledger_guid')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ledger_gst_registration_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_gst_registration_detail_ledger_guid'), ['ledger_guid'], unique=False)

    op.create_table('state_wise_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gst_detail_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state_name', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['gst_detail_id'], ['gst_detail.id'], name=op.f('fk_state_wise_detail_gst_detail_gst_detail_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('state_wise_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_wise_detail_gst_detail_id'), ['gst_detail_id'], unique=False)

    op.create_table('error_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sync_context_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_num', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error', mysql.LONGTEXT(), nullable=False),
    sa.Column('xml_part', mysql.LONGTEXT(), nullable=False),
    sa.Column('error_trace', mysql.LONGTEXT(), nullable=False),
    sa.ForeignKeyConstraint(['sync_context_id'], ['sync_context.id'], name=op.f('fk_error_info_sync_context_sync_context_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('error_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_info_sync_context_id'), ['sync_context_id'], unique=False)

    op.create_table('vch_ledger_entries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ledger_entry_type', mysql.VARCHAR(length=21), nullable=False),
    sa.Column('ledger_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('voucher_guid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('all_inventory_entries_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('index_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ledger_name', mysql.LONGTEXT(), nullable=False),
    sa.Column('ledger_tax_type', mysql.LONGTEXT(), nullable=True),
    sa.Column('ledger_type', mysql.LONGTEXT(), nullable=True),
    sa.Column('is_deemed_positive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('amount_amount', mysql.DECIMAL(precision=20, scale=4), nullable=False),
    sa.Column('amount_currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('amount_forex_amount', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_forex_currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('amount_rate_of_exchange', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_is_debit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['all_inventory_entries_id'], ['vch_inventory_entries.id'], name=op.f('fk_vch_ledger_entries_vch_inventory_entries_all_inventory_entri')),
    sa.ForeignKeyConstraint(['voucher_guid'], ['vouchers.guid'], name=op.f('fk_vch_ledger_entries_vouchers_voucher_guid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vch_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vch_ledger_entries_voucher_guid'), ['voucher_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_vch_ledger_entries_all_inventory_entries_id'), ['all_inventory_entries_id'], unique=False)

    op.create_table('vch_batch_allocations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_inventory_entry_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufactured_on', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('tracking_no', mysql.LONGTEXT(), nullable=True),
    sa.Column('order_no', mysql.LONGTEXT(), nullable=True),
    sa.Column('godown_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('batch_name', mysql.LONGTEXT(), nullable=True),
    sa.Column('order_due_date_due_on_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('order_due_date_in_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_due_date_in_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('expiry_period_due_on_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('expiry_period_in_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expiry_period_in_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('amount_amount', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('amount_forex_amount', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_forex_currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('amount_rate_of_exchange', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_is_debit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('actual_quantity_unit', mysql.LONGTEXT(), nullable=True),
    sa.Column('actual_quantity_quantity', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('billed_quantity_unit', mysql.LONGTEXT(), nullable=True),
    sa.Column('billed_quantity_quantity', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['base_inventory_entry_id'], ['vch_inventory_entries.id'], name=op.f('fk_vch_batch_allocations_vch_inventory_entries_base_inventory_e')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vch_batch_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vch_batch_allocations_base_inventory_entry_id'), ['base_inventory_entry_id'], unique=False)

    op.create_table('hsn_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ledger_guid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('applicable_from', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('hsn_description', mysql.LONGTEXT(), nullable=False),
    sa.Column('hsn_code', mysql.LONGTEXT(), nullable=False),
    sa.Column('hsn_classification_name', mysql.LONGTEXT(), nullable=False),
    sa.Column('source', mysql.LONGTEXT(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_guid'], ['ledgers.guid'], name=op.f('fk_hsn_detail_ledgers_ledger_guid')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('hsn_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hsn_detail_ledger_guid'), ['ledger_guid'], unique=False)

    op.create_table('contact_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ledger_guid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country_iso_code', mysql.LONGTEXT(), nullable=False),
    sa.Column('is_default_whats_app_number', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('name', mysql.LONGTEXT(), nullable=False),
    sa.Column('phone_number', mysql.LONGTEXT(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_guid'], ['ledgers.guid'], name=op.f('fk_contact_detail_ledgers_ledger_guid')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('contact_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_detail_ledger_guid'), ['ledger_guid'], unique=False)

    op.create_table('multi_address',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ledger_guid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address_name', mysql.LONGTEXT(), nullable=False),
    sa.Column('address_lines', mysql.LONGTEXT(), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pin_code', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('contact_person', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('mobile_no', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fax_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('pan_number', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('vat_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('cst_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('excise_nature_of_purchase', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('excise_registration_no', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('excise_import_registration_no', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('import_export_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('gst_dealer_type', mysql.LONGTEXT(), nullable=False),
    sa.Column('is_other_territory_assessee', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('gstin', mysql.VARCHAR(length=17), nullable=True),
    sa.ForeignKeyConstraint(['ledger_guid'], ['ledgers.guid'], name=op.f('fk_multi_address_ledgers_ledger_guid')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('multi_address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_multi_address_ledger_guid'), ['ledger_guid'], unique=False)

    op.create_table('mailing_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ledger_guid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('adress_lines', mysql.LONGTEXT(), nullable=False),
    sa.Column('applicable_from', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('mailing_name', mysql.LONGTEXT(), nullable=False),
    sa.Column('country', mysql.LONGTEXT(), nullable=True),
    sa.Column('state', mysql.LONGTEXT(), nullable=True),
    sa.Column('pin_code', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_guid'], ['ledgers.guid'], name=op.f('fk_mailing_detail_ledgers_ledger_guid')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('mailing_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mailing_detail_ledger_guid'), ['ledger_guid'], unique=False)

    op.create_table('sync_context_attempts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sync_context_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sync_session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attempt_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('completed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('status', mysql.LONGTEXT(), nullable=False),
    sa.Column('pages_completed', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_page', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_message', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['sync_context_id'], ['sync_context.id'], name=op.f('fk_sync_context_attempts_sync_context_sync_context_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_session_id'], ['sync_sessions.id'], name=op.f('fk_sync_context_attempts_sync_sessions_sync_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sync_context_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_context_attempts_sync_session_id'), ['sync_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_context_attempts_sync_context_id'), ['sync_context_id'], unique=False)

    op.create_table('bill_allocations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('all_ledger_entry_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bill_type', mysql.LONGTEXT(), nullable=True),
    sa.Column('name', mysql.LONGTEXT(), nullable=True),
    sa.Column('bill_credit_period_due_on_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('bill_credit_period_in_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bill_credit_period_in_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('amount_amount', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('amount_forex_amount', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_forex_currency', mysql.LONGTEXT(), nullable=True),
    sa.Column('amount_rate_of_exchange', mysql.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('amount_is_debit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['all_ledger_entry_id'], ['vch_ledger_entries.id'], name=op.f('fk_bill_allocations_vch_ledger_entries_all_ledger_entry_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('bill_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_allocations_all_ledger_entry_id'), ['all_ledger_entry_id'], unique=False)

    op.drop_table('otp')
    # ### end Alembic commands ###
